### ISSUE TITLE
All sensors are unavailable

### ISSUE THREAD

**Issue by Dotpitch01** [RalfWinter/lambda-heatpump-modbus-tcp-HA#4]
Got proudly my EUL13 two days ago.
Copied your code into the configuration.yaml.
This allowed me to add a new card "Wärmepumpe" to the dashboard.
Adding entities was no problem. But all of them are grey - not available.

In your script I adjusted only the ip-adress of the heatpump. 

Do I have to activate anything on the Lambda Panel? 
My plumber told me that I would get any registration key from Lambda, to reach a higher User-Level. Or isn´t that an issue?

**Comment by thecem** [comment]
Could you post your config ( only the Modbus part) ?

**Comment by Dotpitch01** [comment]
Sorry my fault.
IP-adress wasn‘t the right one…
Thank you Mr. Winter for that perfect script and thecem being so kind helping.

**Comment by Dotpitch01** [comment]
Problem solved
