### ISSUE TITLE
VNC password

### ISSUE THREAD

**Issue by anbie** [RalfWinter/lambda-heatpump-modbus-tcp-HA#5]
What ‘s the best way to obtain the VNC password for the Lambda heat pump. Do I need to request if from Lambda or the heat pump installers? Or is there a way to extract it somewhere else?

Thanks in advance

**Comment by RalfWinter** [comment]
Hello my friend, I had the request. The installer does not know the VNC password, you need to talk to Lambda support team to request the password. I assume it is the same in every installation, access to the installation is managed by individual VPN.

Cheers...Ralf

**Comment by anbie** [comment]
Thanks, Ralf. I'll get a mail out to Lambda.
