### ISSUE TITLE
Error with "count: 1" , receiving no values

### ISSUE THREAD

**Issue by FBrokelmann** [RalfWinter/lambda-heatpump-modbus-tcp-HA#7]
Hi Ralf, thank you very much for your yaml-config!  :-)

I try to get modbus up & running in my HA-Installation (which I installed one week ago, I am new to HA). Unfortunately it dosn't work, maybe you can help me on my issue:

- Using your YAML configuration without changes (except the IP-adress) I get a validation error:

![image](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/94867884/726fb69a-cf7b-4af6-8b1b-9ef4d1ea72a7)

- After deleting the line "count: 1", the validation is green. After reloading the yaml-konfig alle entities appear, but without connextion to the heatpump. 
![image](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/94867884/351a2302-d67e-4f3c-9d50-fccefa271941)

Do you have any idea, where this problem may come from?

My setting is as following:
Lambda
![image](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/94867884/3f9fb900-dbc8-4440-8418-0391f6fb8012)

HomeAssistant:
![image](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/94867884/cf993d72-fc04-4936-a3d4-1f71e1f90c42)

Thank you very much for your time!

**Comment by RalfWinter** [comment]
Hi there,
your HA screenshot says "Operating System 11.0", so I guess you run it on Windows. My yaml file has been generated on Linux, probably there is a format problem, Windows needs CR/LF where Linux text files only use CR at the end of each line.
I suggest you load the yaml on windows notepad and see whether the lines break correctly.

Regarding your connection issue: do you have telnet on your HA machine and can do a "_telnet <ip-of-lambda> 502_" ? This should give you following output:

Connected to <ip-of-lambda>.
Escape character is '^]'.

If not you have a connection issue. On Android you can download "Modbus Monitor" and check whether your Lambda-heatpump responds to requests.

Cheers....Ralf

**Comment by FBrokelmann** [comment]
Hi Ralf, 
thanx again for your super fast response! I was able to connect with modbus monitor on my windows maschine before my post , so I knew it has to be the on the HA side. It works fine now, I found a typo in the IP-Adress... (I'm so sorry).

Regarding my problem with "count: 1": There were changes  in 2023.10 in modbus integration (see https://github.com/home-assistant/core/issues/101421). The solution is to remove the parameter (as I did without intuitevly). maybe you want to update your code (or at least be aware of a potential problem during your next update...) ;-)
 
By the way: I am running a raspberry PI 4 with the latest Version. 

Cheers  Falk

**Comment by RalfWinter** [comment]
Thanks for the heads-up, Falk! I am just testing the change without the "count"-lines in my (older-version) HA system, looks good so far. I will publish a new version with all "count"-lines removed soon. No update required on your side in case you already removed all lines starting with "count".

Cheers...Ralf
