### ISSUE TITLE
Heating circuit operation mode (register 5006)

### ISSUE THREAD

**Issue by thecem** [RalfWinter/lambda-heatpump-modbus-tcp-HA#8]
I get for register 5006 and 5106 the value -300.0.

Do you have here the mode number?

thx.

**Comment by RalfWinter** [comment]
Sorry, can't help here. OP mode numbers go from 0 to 7, -300 must be an  error.
Cheers....Ralf

**Comment by thecem** [comment]
The question is if you have here a Number? If so lambda has to configure something that this is readable.

**Comment by RalfWinter** [comment]
Yes, I have OP mode "3" (auto-heating):
![Screenshot_20231023_201921_Home Assistant](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/122975008/05ba4cc5-8afa-49fd-a5be-d34855b67e8e)

**Comment by thecem** [comment]
Thx Ralf, so there will be a config action from lambda, to let me access the OP Mode register, additional I don’t have the „soll-temp“ (set point flow line/ 5005&5105).

What for a user level do you have?

thx

**Comment by RalfWinter** [comment]
My heatpump is at v1.20 SP1, my HA installation at 2022.11.4, the "user level" at the heatpump when logged in is "1". Lambda does not give higher user levels to end users.

Cheers....Ralf

**Comment by RalphDiesinger** [comment]
> Thx Ralf, so there will be a config action from lambda, to let me access the OP Mode register, additional I don’t have the „soll-temp“ (set point flow line/ 5005&5105).
> 
> What for a user level do you have?
> 
> thx

Hello
does reading the registers work with the new yaml file ? I'm also interested, because I'm getting my Lambda mounted in January and would like to connect it to HomeAssistant as well.
Greetings Ralph

**Comment by RalfWinter** [comment]
Hi Ralph,
yes, of course, I use the new yaml file in my own setup successfully. Compared to the original yaml file I made just 2 changes: removed a bug which was not seen on my installation and added new parameters as published by Lambda earlier this year. However, I could not yet test the new parameters because my Lambda is still on a 2021 SW-level which does not provide the new values which were introduced this year.

Cheers....Ralf

**Comment by RalphDiesinger** [comment]
> Hi Ralph, yes, of course, I use the new yaml file in my own setup successfully. Compared to the original yaml file I made just 2 changes: removed a bug which was not seen on my installation and added new parameters as published by Lambda earlier this year. However, I could not yet test the new parameters because my Lambda is still on a 2021 SW-level which does not provide the new values which were introduced this year.
> 
> Cheers....Ralf

Hi Ralf,
thanks for the info. As soon as my heat pump is installed, I will also test.
Greetings Ralph

**Comment by thecem** [comment]
> > Thx Ralf, so there will be a config action from lambda, to let me access the OP Mode register, additional I don’t have the „soll-temp“ (set point flow line/ 5005&5105).
> > What for a user level do you have?
> > thx
> 
> Hello does reading the registers work with the new yaml file ? I'm also interested, because I'm getting my Lambda mounted in January and would like to connect it to HomeAssistant as well. Greetings Ralph

I use my own yaml, but the only difference is the `input_type: holding`.

I had in the past a similar issue where lambda had to configure something, afterwards it worked.

my EU08L is on:

![IMG_4092](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/46648579/380e162d-d736-4ed5-a05a-18e0180bfa69)

**Comment by thecem** [comment]
One more question, belong the readings from register 5006 in your case to the heating circuit mode in lambda gui?

![IMG_0026](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/46648579/834d4919-0821-420c-8b5f-2f6df2a3efee)

I can’t set via write to register 5006 this to a different mode, in the drop down menu.
Only if I set it in the lambda gui to auto i‘am able to see that the icons switch to the modes corresponding to the values in the register, but the drop down don’t switch.


![IMG_0028](https://github.com/RalfWinter/lambda-heatpump-modbus-tcp-HA/assets/46648579/21566a7f-74cc-46a9-a96e-fc62ecb6c203)

**Comment by RalphDiesinger** [comment]
Hello,
maybe it has to be that Lambda has to change something on the register. In register 5006/5106 the unit is [0.1°C] and not register 5001 {No. as is comparable to the other registers. See Modbus documentation on the website.
________________________________
Von: thecem ***@***.***>
Gesendet: Montag, 23. Oktober 2023 06:38
An: RalfWinter/lambda-heatpump-modbus-tcp-HA ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [RalfWinter/lambda-heatpump-modbus-tcp-HA] Heating circuit operation mode (register 5006) (Issue #8)


I get for register 5006 and 5106 the value -300.0.

Do you have hier the mode number?

thx.

**Comment by thecem** [comment]
In between I get the information from lambda, that the actual SW is not supporting the values, like in the old controller software. There will be an update.
